```{r include=FALSE}
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  comment = '#>',
  collapse = TRUE,
  fig.width=8,
  fig.height=6,
  cache.path = "cache/"
)
```

In this example, we collect specimen records across different cities using GBIF data from the `rgbif` package.

_Load libraries_

```{r load}
library("rgbif")
library("ggplot2")
library("plyr")
library("RCurl")
library("RColorBrewer")
```

_Get bounding boxes for some cites_

Bounding lat/long data is from [here](https://raw.github.com/amyxzhang/boundingbox-cities/master/boundbox.txt).

```{r box}
rawdat <- getURL('https://raw.githubusercontent.com/amyxzhang/boundingbox-cities/master/boundbox.txt')
dat <- read.table(text = rawdat, header = FALSE, sep="\t", col.names=c("city","minlat","maxlon","maxlat","minlon"))
dat <- data.frame(city=dat$city, minlon=dat$minlon, minlat=dat$minlat, maxlon=dat$maxlon, maxlat=dat$maxlat)
```

```{r newsearch}
getdata <- function(x){
  coords <- as.numeric(x[c('minlon','minlat','maxlon','maxlat')])
  num <- occ_search(geometry = coords)$meta$count
  data.frame(city=x['city'], richness=num, stringsAsFactors = FALSE)
}
```

```{r cache=TRUE}
out <- apply(dat, 1, getdata)
```

_Merge to original table_

```{r}
out <- merge(dat, ldply(out), by="city")
```

_Add centroids from bounding boxes_

```{r}
out <- transform(out, lat = (minlat+maxlat)/2, lon = (minlon+maxlon)/2)
```

_Plot data_

```{r}
mapp <- map_data('world')
ggplot(mapp, aes(long, lat)) +
  geom_polygon(aes(group=group), fill="white", alpha=0, color="black", size=0.4) +
  geom_point(data=out, aes(lon, lat, color=richness), size=5, alpha=0.8) +
  scale_color_continuous(low = "#60E1EE", high = "#0404C8") +
  labs(x="", y="") +
  theme_grey(base_size=14) +
  theme(legend.position = "bottom", legend.key = element_blank()) +
  guides(color = guide_legend(keywidth = 2))
```
